/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;
using System.Runtime.Serialization;

namespace Vulkan
{
    [Serializable]
    internal class VULKANDEVICE_NO_ACTIVE_DEVICE : Exception
    {
        public VULKANDEVICE_NO_ACTIVE_DEVICE()
        {
        }

        public VULKANDEVICE_NO_ACTIVE_DEVICE(string message) : base(message)
        {
        }

        public VULKANDEVICE_NO_ACTIVE_DEVICE(string message, Exception innerException) : base(message, innerException)
        {
        }

        protected VULKANDEVICE_NO_ACTIVE_DEVICE(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}