/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;
using System.Runtime.Serialization;

namespace Vulkan
{
    [Serializable]
    internal class VULKAN_ERROR_OUT_OF_DATE_KHR : Exception
    {
        public VULKAN_ERROR_OUT_OF_DATE_KHR()
        {
        }

        public VULKAN_ERROR_OUT_OF_DATE_KHR(string message) : base(message)
        {
        }

        public VULKAN_ERROR_OUT_OF_DATE_KHR(string message, Exception innerException) : base(message, innerException)
        {
        }

        protected VULKAN_ERROR_OUT_OF_DATE_KHR(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}