/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;
using System.Collections.Generic;

namespace Vulkan
{

	public partial class CommandPool : INonDispatchableHandleMarshalling
	{
		internal CommandPool() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class BufferView : INonDispatchableHandleMarshalling
	{
		internal BufferView() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class ImageView : INonDispatchableHandleMarshalling
	{
		internal ImageView() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public class ShaderModule : INonDispatchableHandleMarshalling
	{
		internal ShaderModule() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class Pipeline : INonDispatchableHandleMarshalling
	{
		internal Pipeline() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class PipelineLayout : INonDispatchableHandleMarshalling
	{
		internal PipelineLayout() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class Sampler : INonDispatchableHandleMarshalling
	{
		internal Sampler() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DescriptorSet : INonDispatchableHandleMarshalling
	{
		internal DescriptorSet() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DescriptorPool : INonDispatchableHandleMarshalling
	{
		internal DescriptorPool() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class Fence : INonDispatchableHandleMarshalling
	{
		internal Fence() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class Semaphore : INonDispatchableHandleMarshalling
	{
		internal Semaphore() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class Event : INonDispatchableHandleMarshalling
	{
		internal Event() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class QueryPool : INonDispatchableHandleMarshalling
	{
		internal QueryPool() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class RenderPass : INonDispatchableHandleMarshalling
	{
		internal RenderPass() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class PipelineCache : INonDispatchableHandleMarshalling
	{
		internal PipelineCache() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class ObjectTableNvx : INonDispatchableHandleMarshalling
	{
		internal ObjectTableNvx() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class IndirectCommandsLayoutNvx : INonDispatchableHandleMarshalling
	{
		internal IndirectCommandsLayoutNvx() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DescriptorUpdateTemplateKHR : INonDispatchableHandleMarshalling
	{
		internal DescriptorUpdateTemplateKHR() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class SamplerYcbcrConversionKHR : INonDispatchableHandleMarshalling
	{
		internal SamplerYcbcrConversionKHR() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class ValidationCacheExt : INonDispatchableHandleMarshalling
	{
		internal ValidationCacheExt() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DisplayKHR : INonDispatchableHandleMarshalling
	{
		internal DisplayKHR() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DisplayModeKHR : INonDispatchableHandleMarshalling
	{
		internal DisplayModeKHR() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class SwapchainKHR : INonDispatchableHandleMarshalling
	{
		internal SwapchainKHR() {}

		internal UInt64 m;

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}

	public partial class DebugReportCallbackExt : INonDispatchableHandleMarshalling
	{
		internal DebugReportCallbackExt() {}

		internal UInt64 m;

		~DebugReportCallbackExt()
		{
			int Shit = 0;
		}

		UInt64 INonDispatchableHandleMarshalling.Handle {
			get {
				return m;
			}
		}
	}
}
